Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;

namespace BookStore.Controllers
{
    public class GioHangController : Controller
    {
        CSDLContext db = new CSDLContext();
        // GET: GioHang
        public ActionResult Index()
        {
            List<GioHang> giohang = Session["giohang"] as List<GioHang>;
            return View(giohang);
        }

        public RedirectResult ThemVaoGio(int MaSach)
        {
            if (Session["giohang"] == null)
            {
                Session["giohang"] = new List<GioHang>();
            }
            List<GioHang> giohang = Session["giohang"] as List<GioHang>;

            if (giohang.FirstOrDefault(m => m.MaSach == MaSach) == null)
            {
                Sach pd = db.Saches.Find(MaSach);
                GioHang newItem = new GioHang()
                {
                    MaSach = MaSach,
                    TenSach = pd.TenSach,
                    SoLuong = 1,
                    HinhAnh = pd.HinhAnh,
                    Gia = pd.Gia
                };
                giohang.Add(newItem);
            }
            else
            {
                GioHang cardItem = giohang.FirstOrDefault(m => m.MaSach == MaSach);
                cardItem.SoLuong++;
            }
            return Redirect(Request.UrlReferrer.ToString());
        }
        public RedirectToRouteResult SuaSoLuong(int MaSach, int soluongmoi)
        {
            List<GioHang> giohang = Session["giohang"] as List<GioHang>;
            GioHang itemSua = giohang.FirstOrDefault(m => m.MaSach == MaSach);
            if (itemSua != null)
            {
                itemSua.SoLuong= soluongmoi;
            }
            return RedirectToAction("Index");
        }
        public RedirectToRouteResult XoaKhoiGio(int MaSach)
        {
            List<GioHang> giohang = Session["giohang"] as List<GioHang>;
           GioHang itemXoa = giohang.FirstOrDefault(m => m.MaSach == MaSach);
            if (itemXoa != null)
            {
                giohang.Remove(itemXoa);

            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using PagedList;

namespace BookStore.Controllers
{
    public class HomeController : Controller
    {
        CSDLContext db = new CSDLContext();
        public ActionResult Index()
        {
            List<Sach> kynang = db.Saches.Where(a => a.MaLoai == 1).OrderBy(a => a.MaSach).Take(8).ToList();
            List<Sach> thieunhi = db.Saches.Where(a => a.MaLoai == 2).OrderBy(a => a.MaSach).Take(8).ToList();
            List<Sach> vanhoc = db.Saches.Where(a => a.MaLoai == 3).OrderBy(a => a.MaSach).Take(8).ToList();
            List<Sach> slider = db.Saches.OrderByDescending(a => a.MaSach).Take(5).ToList();
            ViewBag.kynang = kynang;
            ViewBag.thieunhi = thieunhi;
            ViewBag.vanhoc = vanhoc;
            ViewBag.slider = slider;
            return View();
        }

        public ActionResult DanhMucSach(int? page, int maLoai, int? min, int? max)
        {
            min = (min ?? 10000);
            max = (max ?? 500000);
            ViewBag.min = min;
            ViewBag.max = max;
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            var ds = db.Saches.Where(t => (t.Gia <= max) && (t.Gia >= min)).OrderBy(x => x.TenSach).Where(a => a.MaLoai == maLoai).ToPagedList(pageNumber, pageSize);
            var pagecount = ds.PageCount;
            ViewBag.pc = pagecount;
            ViewBag.pageNumber = pageNumber;
            Loai br = db.Loais.Find(maLoai);
            ViewBag.br = br;
            ViewBag.maLoai = maLoai;
            ViewBag.ds = ds;
            return View();
        }

        public ActionResult ChiTietSach(int id)
        {
            Sach pd = db.Saches.Find(id);
            Loai br = db.Loais.Find(pd.MaLoai);
            ViewBag.pd = pd;
            ViewBag.br = br;
            return View();
        }

        [HttpGet]
        public ActionResult TimKiemTheoTen(string name, int? page)
        {
            ViewBag.name = name;
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            //List<Product> ds = db.Products.Where(t => t.ProductName.Contains(name)).OrderBy(x => x.ProductName).ToList();
            var ds = db.Saches.Where(t => t.TenSach.Contains(name)).OrderBy(x => x.TenSach).ToPagedList(pageNumber, pageSize);
            var pagecount = ds.PageCount;
            //var pagecount = ds.ToPagedList(pageNumber, pageSize).PageCount;
            ViewBag.pc = pagecount;
            ViewBag.pageNumber = pageNumber;
            return View(ds);
            //return View(db.Products.Where(t => t.ProductName.Contains(name)).OrderBy(x => x.ProductName).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult GioiThieu()
        {
            return View();
        }
        public ActionResult LienHe()
        {
            return View();
        }
    }
}

Views/Home/ChiTietSach.cshtml
@{
    ViewBag.Title = "ChiTietSach";
    Layout = "~/Views/Shared/_LayoutFreecss.cshtml";
}

<section id="aa-product-details">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-product-details-area">
                    <div class="aa-product-details-content">
                        <div class="row">
                            <!-- Modal view slider -->
                            <div class="col-md-5 col-sm-5 col-xs-12">
                                <div class="aa-product-view-slider">
                                    <div id="demo-1" class="simpleLens-gallery-container">
                                        <div class="simpleLens-container">
                                            <div class="simpleLens-big-image-container"><a data-lens-image="@Url.Content("~/Image")/@ViewBag.pd.HinhAnh" class="simpleLens-lens-image"><img src="@Url.Content("~/Image")/@ViewBag.pd.HinhAnh" class="simpleLens-big-image"></a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Modal view content -->
                            <div class="col-md-7 col-sm-7 col-xs-12">
                                <div class="aa-product-view-content">
                                    <h3>@ViewBag.pd.TenSach</h3>
                                    <div class="aa-price-block">
                                        <p class="aa-product-avilability">Tác Giả: <span>@ViewBag.pd.TacGia</span></p>
                                        <p class="aa-product-avilability">NXB: <span>@ViewBag.pd.NXB</span></p>
                                        <span class="aa-product-view-price">@ViewBag.pd.Gia.ToString("#,##0").Replace(',', '.') VNĐ</span>
                                        <p class="aa-product-avilability">Mô tả: <span>@ViewBag.pd.Description</span></p>

                                    </div>

                                    <div class="aa-prod-quantity">

                                        <p class="aa-prod-category">
                                            Thể loại: <a href="#">@ViewBag.br.TenLoai</a>
                                        </p>
                                        <p class="aa-prod-category">
                                            NCC: <a href="#">PNO</a>
                                        </p>
                                    </div>
                                    <div class="aa-prod-view-bottom">
                                        <a class="aa-add-to-cart-btn" href="@Url.Action("ThemVaoGio", "GioHang", new { MaSach = Url.RequestContext.RouteData.Values["id"] })">Add To Cart</a>
                                        <a href="@Url.Action("Index", "Home")" role="button" class="btn btn-default">VỀ TRANG CHỦ</a>
                                    </div>
                                    <br />
                                    <br />
                                    <br />
                                    <br />
                                    <br />
                                    <br />
                                    <br />
                                    <br />
                                    <br />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Home/DanhMucSach.cshtml
@{
    ViewBag.Title = "DanhMucSach";
    Layout = "~/Views/Shared/_LayoutFreecss.cshtml";
}

<section id="aa-catg-head-banner">
    @*<img src="" width="1550" height="400" style="opacity:0.5" alt="fashion img">*@
    <div class="aa-catg-head-banner-area">
        <div class="container">
            <div class="aa-catg-head-banner-content">
                @*<h2>Fashion</h2>*@
                <ol class="breadcrumb">
                    <li><a href="@Url.Action("Index","Home")">Home</a></li>
                    <li class="active">@ViewBag.br.TenLoai</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- / catg header banner section -->
<!-- product category -->
<section id="aa-product-category">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-8 col-md-push-3">
                <div class="aa-product-catg-content">
                    <div class="aa-product-catg-head">
                        @*<div class="aa-product-catg-head-left">
                                <form action="" class="aa-sort-form">
                                    <label for="">Sort by</label>
                                    <select name="">
                                        <option value="1" selected="Default">Default</option>
                                        <option value="2">Name</option>
                                        <option value="3">Price</option>
                                    </select>
                                </form>

                            </div>*@
                        <div class="aa-product-catg-body">
                            <ul class="aa-product-catg">
                                <!-- start single product item -->
                                @foreach (var item in ViewBag.ds)
                                {
                                    <li>
                                        <figure>
                                            <a class="aa-product-img" href="@Url.Action("ChiTietSach", "Home", new { id = item.MaSach })"><img height="300" width="250" src="@Url.Content("~/Image")/@item.HinhAnh " alt="@item.HinhAnh"></a>
                                            <a class="aa-add-card-btn" href="@Url.Action("ThemVaoGio", "GioHang", new {MaSach = item.MaSach })"><span class="fa fa-shopping-cart"></span>Add To Cart</a>
                                            <figcaption>
                                                <h4 class="aa-product-title"><a href="#">@item.TenSach</a></h4>
                                                <span class="aa-product-price">@item.Gia.ToString("#,##0").Replace(',', '.') VNĐ</span>
                                                <p class="aa-product-descrip">@item.Description</p>
                                            </figcaption>
                                        </figure>
                                        <!-- product badge -->
                                    </li>
                                }
                            </ul>

                        </div>
                        <div class="aa-product-catg-pagination">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        @if ((ViewBag.pageNumber - 1) != 0)
                                        {
                                            <a href="@Url.Action("DanhMucSach", "Home", new { page = ViewBag.pageNumber - 1, maLoai = ViewBag.maLoai, min = ViewBag.min, max = ViewBag.max})" aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        }
                                        else
                                        {
                                            <a aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        }

                                    </li>
                                    @for (int i = 1; i < ViewBag.pc + 1; i++)
                                    {
                                        <li><a href="@Url.Action("DanhMucSach", "Home", new { page = i, maLoai = ViewBag.maLoai, min = ViewBag.min, max = ViewBag.max})" title="@i">@i</a></li>
                                    }
                                    <li>
                                        @if ((ViewBag.pageNumber + 1) < (ViewBag.pc + 1))
                                        {
                                            <a href="@Url.Action("DanhMucSach", "Home", new { page = ViewBag.pageNumber + 1 , maLoai = ViewBag.maLoai, min = ViewBag.min, max = ViewBag.max})" aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        }
                                        else
                                        {
                                            <a aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        }

                                    </li>
                                </ul>
                            </nav>
                        </div>



                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-md-pull-9">
                    <aside class="aa-sidebar">
                        <!-- single sidebar -->
                        <div class="aa-sidebar-widget">

                        </div>
                        <!-- single sidebar -->

                    </aside>
                </div>

            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-md-pull-9">
                <aside class="aa-sidebar">
                    <div class="aa-sidebar-widget">
                        <h3>Chọn thể loại</h3>
                        <ul class="aa-catg-nav">
                            <li><a href="@Url.Action("DanhMucSach","Home", new { maLoai = 1 })">Kỹ Năng</a></li>
                            <li><a href="@Url.Action("DanhMucSach","Home", new { maLoai = 2 })">Thiếu Nhi</a></li>
                            <li><a href="@Url.Action("DanhMucSach","Home", new { maLoai = 3 })">Văn Học</a></li>
                        </ul>
                    </div>

                    <div class="aa-sidebar-widget">
                        <h3>Chọn theo khoảng giá</h3>
                        <ul class="aa-catg-nav">
                            <li><a href="@Url.Action("DanhMucSach", "Home", new { min = 10000, max = 50000, maLoai = ViewBag.maLoai})">10.000 - 50.000 VNĐ</a></li>
                            <li><a href="@Url.Action("DanhMucSach", "Home", new { min = 50000, max = 100000, maLoai = ViewBag.maLoai})">50.000 - 100.000 VNĐ</a></li>
                            <li><a href="@Url.Action("DanhMucSach", "Home", new { min = 100000, max = 150000, maLoai = ViewBag.maLoai})">100.000 - 150.000 VNĐ</a></li>
                            <li><a href="@Url.Action("DanhMucSach", "Home", new { min = 150000, max = 200000, maLoai = ViewBag.maLoai})">150.000 - 200.000 VNĐ</a></li>
                            <li><a href="@Url.Action("DanhMucSach", "Home", new { min = 200000, max = 1000000, maLoai = ViewBag.maLoai})">> 200.000 VNĐ</a></li>
                        </ul>

                    </div>

                </aside>

            </div>
        </div>
    </div>
</section>


@*@Html.PagedListPager((IPagedList)ViewBag.ds, sotrang => Url.Action("Bitis", new { page = sotrang}))*@

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutFreecss.cshtml";
}

<!-- Start slider -->
<section id="aa-slider">
    <div class="aa-slider-area">
        <div id="sequence" class="seq">
            <div class="seq-screen">
                <ul class="seq-canvas">
                    <!-- single slide item -->
                    @foreach (var item in ViewBag.slider)
                    {
                        <li>
                            <div class="seq-model">
                                <img data-seq src="@Url.Content("~/Image")/@item.HinhAnh" alt="@item.HinhAnh" />
                            </div>
                            <div class="seq-title">
                                <span data-seq>Save Up to 50% Off</span>
                                <h2 data-seq>Sách Hot</h2>
                                <p data-seq>Sự hài lòng của quý khách là niềm vinh hạnh của chúng tôi.</p>
                                @*<a data-seq href="#" class="aa-shop-now-btn aa-secondary-btn">SHOP NOW</a>*@
                            </div>
                        </li>
                    }
                    <!-- single slide item -->
                </ul>
            </div>
            <!-- slider navigation btn -->
            <fieldset class="seq-nav" aria-controls="sequence" aria-label="Slider buttons">
                <a type="button" class="seq-prev" aria-label="Previous"><span class="fa fa-angle-left"></span></a>
                <a type="button" class="seq-next" aria-label="Next"><span class="fa fa-angle-right"></span></a>
            </fieldset>
        </div>
    </div>
</section>
<!-- / slider -->
<!-- Start Promo section -->
<!-- / Promo section -->
<!-- Products section -->
<section id="aa-product">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="aa-product-area">
                        <div class="aa-product-inner">
                            <!-- start prduct navigation -->
                            <ul class="nav nav-tabs aa-products-tab">
                                <li class="active"><a href="#thieunhi" data-toggle="tab">Thiếu Nhi</a></li>
                                <li><a href="#kynang" data-toggle="tab">Kỹ Năng</a></li>
                                <li><a href="#vanhoc" data-toggle="tab">Văn Học</a></li>

                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <!-- Start men product category -->
                                <div class="tab-pane fade in active" id="thieunhi">
                                    <ul class="aa-product-catg">
                                        <!-- start single product item -->
                                        @foreach (var item in ViewBag.thieunhi)
                                        {
                                            <li>
                                                <figure>
                                                    <a class="aa-product-img" href="@Url.Action("ChiTietSach", "Home", new { id = item.MaSach })"><img height="300" width="250" src="@Url.Content("~/Image")/@item.HinhAnh" alt="@item.HinhAnh"></a>
                                                    <a class="aa-add-card-btn" href="@Url.Action("ThemVaoGio", "GioHang", new { MaSach = item.MaSach })"><span class="fa fa-shopping-cart"></span>Add To Cart</a>
                                                    <figcaption>
                                                        <h4 class="aa-product-title"><a href="#">@item.TenSach</a></h4>
                                                        <span class="aa-product-price">@item.Gia.ToString("#,##0").Replace(',', '.') VNĐ</span>
                                                    </figcaption>
                                                </figure>
                                            </li>
                                        }
                                    </ul>
                                </div>
                                <!-- / men product category -->
                                <!-- start women product category -->
                                <div class="tab-pane fade" id="kynang">
                                    <ul class="aa-product-catg">
                                        <!-- start single product item -->
                                        @foreach (var item in ViewBag.kynang)
                                        {
                                            <li>
                                                <figure>
                                                    <a class="aa-product-img" href="@Url.Action("ChiTietSach", "Home", new { id = item.MaSach })"><img height="300" width="250" src="@Url.Content("~/Image")/@item.HinhAnh" alt="@item.HinhAnh"></a>
                                                    <a class="aa-add-card-btn" href="@Url.Action("ThemVaoGio", "GioHang", new { MaSach = item.MaSach })"><span class="fa fa-shopping-cart"></span>Add To Cart</a>
                                                    <figcaption>
                                                        <h4 class="aa-product-title"><a href="#">@item.TenSach</a></h4>
                                                        <span class="aa-product-price">@item.Gia.ToString("#,##0").Replace(',', '.') VNĐ</span>
                                                    </figcaption>
                                                </figure>
                                            </li>
                                        }
                                    </ul>
                                </div>
                                <!-- / women product category -->
                                <!-- start sports product category -->
                                <div class="tab-pane fade" id="vanhoc">
                                    <ul class="aa-product-catg">
                                        <!-- start single product item -->
                                        @foreach (var item in ViewBag.vanhoc)
                                        {
                                            <li>
                                                <figure>
                                                    <a class="aa-product-img" href="@Url.Action("ChiTietSach", "Home", new { id = item.MaSach })"><img height="300" width="250" src="@Url.Content("~/Image")/@item.HinhAnh" alt="@item.HinhAnh"></a>
                                                    <a class="aa-add-card-btn" href="@Url.Action("ThemVaoGio", "GioHang", new { MaSach = item.MaSach })"><span class="fa fa-shopping-cart"></span>Add To Cart</a>
                                                    <figcaption>
                                                        <h4 class="aa-product-title"><a href="#">@item.TenSach</a></h4>
                                                        <span class="aa-product-price">@item.Gia.ToString("#,##0").Replace(',', '.') VNĐ</span>
                                                    </figcaption>
                                                </figure>
                                            </li>
                                        }
                                    </ul>
                                </div>
                                <!-- / sports product category -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Home/TimKiemTheoTen.cshtml
@model IEnumerable<BookStore.Models.Sach>
@{
    ViewBag.Title = "TimKiemTheoTen";
    Layout = "~/Views/Shared/_LayoutFreecss.cshtml";
}

<section id="aa-product">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="aa-product-area">
                        <div class="aa-product-inner">
                            <div class="tab-content">
                                <!-- Start men product category -->
                                <div class="tab-pane fade in active">
                                    <ul class="aa-product-catg">
                                        <!-- start single product item -->
                                        <br />
                                        <br />
                                        
                                        @foreach (var item in Model)
                                        {
                                            <li>
                                                <figure>
                                                    <a class="aa-product-img" href="@Url.Action("ChiTietSach", "Home", new { id = item.MaSach })"><img height="300" width="250" src="@Url.Content("~/Image")/@item.HinhAnh" alt="@item.HinhAnh"></a>
                                                    <a class="aa-add-card-btn" href="@Url.Action("ThemVaoGio", "GioHang", new { ProductID = item.MaSach })"><span class="fa fa-shopping-cart"></span>Add To Cart</a>
                                                    <figcaption>
                                                        <h4 class="aa-product-title"><a href="@Url.Action("ChiTietSach", "Home", new { id = item.MaSach })">@item.TenSach</a></h4>
                                                        <span class="aa-product-price">@item.Gia.ToString("#,##0").Replace(',', '.') VNĐ</span>
                                                    </figcaption>
                                                </figure>
                                            </li>
                                        }
                                    </ul>
                                </div>

                            </div>

                        </div>
                        <section id="aa-product-category">
                            <div class="container">
                                <div class="aa-product-catg-content">
                                    <div class="aa-product-catg-pagination">
                                        <nav>
                                            <ul class="pagination">
                                                <li>
                                                    @if ((ViewBag.pageNumber - 1) != 0)
                                                    {
                                                        <a href="@Url.Action("TimKiemTheoTen", "Home", new { page = ViewBag.pageNumber - 1, name = ViewBag.name })" aria-label="Previous">
                                                            <span aria-hidden="true">&laquo;</span>
                                                        </a>
                                                    }
                                                    else
                                                    {
                                                        <a aria-label="Previous">
                                                            <span aria-hidden="true">&laquo;</span>
                                                        </a>
                                                    }

                                                </li>
                                                @for (int i = 1; i < ViewBag.pc + 1; i++)
                                                {
                                                    <li><a href="@Url.Action("TimKiemTheoTen", "Home", new { page = i, name = ViewBag.name })" title="@i">@i</a></li>
                                                }
                                                <li>
                                                    @if ((ViewBag.pageNumber + 1) < (ViewBag.pc + 1))
                                                    {
                                                        <a href="@Url.Action("TimKiemTheoTen", "Home", new { page = ViewBag.pageNumber + 1 , name = ViewBag.name})" aria-label="Next">
                                                            <span aria-hidden="true">&raquo;</span>
                                                        </a>
                                                    }
                                                    else
                                                    {
                                                        <a aria-label="Next">
                                                            <span aria-hidden="true">&raquo;</span>
                                                        </a>
                                                    }

                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>

                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>